# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59cb221d4205eaca72569993689004f87e67d4ad062a8fb5ccfa8aa9fda1a829f8b26c293f78b7ac808f64d6861d93f3e45f7e965272e45fcd329e4c9b3a6008

test:
  secret_key_base: f898683d44dadb80fc871337b5b6c45318f86acbfbc80478464c2e0625f59b8c4eb4c9539075dff6f276e4dc142e369ee8f705ee1b83b098f1577fe3bffc70da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
